In [2]:
import numpy as np
import pandas as pd
import math as m

In [9]:
eye_pos = np.array((0,4,-3))
light_pos = np.array((3,4,0))
position = np.array((0,1,0))
Il = np.array((1, 1, 1))

Ka = np.array((0.1, 0.1, 0.1))
Kd = np.array((1, 1, 1))
Ks = np.array((1, 1, 0))
shininess = 50

N = position * 1/np.linalg.norm(position)
N

array([0., 1., 0.])

In [4]:
ambient = Il * Ka
ambient

array([0.1, 0.1, 0.1])

In [5]:
L = light_pos - position
L

array([3, 3, 0])

In [7]:
L = L * 1/np.linalg.norm(L)
L

array([0.70710678, 0.70710678, 0.        ])

In [10]:
NdotL = max(np.dot(N,L),0)
NdotL

0.7071067811865476

In [11]:
V = eye_pos - position
V

array([ 0,  3, -3])

In [12]:
V = V*1/np.linalg.norm(V)
V

array([ 0.        ,  0.70710678, -0.70710678])

In [13]:
H = L+V
H

array([ 0.70710678,  1.41421356, -0.70710678])

In [14]:
H = H*1/np.linalg.norm(H)
H

array([ 0.40824829,  0.81649658, -0.40824829])

In [15]:
NdotH = max(np.dot(N,H),0)
NdotH

0.816496580927726

In [16]:
diffues = Kd*NdotL*Il
diffues

array([0.70710678, 0.70710678, 0.70710678])

In [17]:
ambient

array([0.1, 0.1, 0.1])

In [18]:
speccular = Ks*pow(NdotH,shininess)*Il
speccular

array([3.9602128e-05, 3.9602128e-05, 0.0000000e+00])

In [19]:
I = ambient + diffues + speccular
I

array([0.80714638, 0.80714638, 0.80710678])